# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-configmap
  namespace: jenkins
data:
  plugins.txt: |-
    kubernetes:1.12.2
    github:1.29.2
    ghprb:1.42.0
    job-dsl:1.70
    durable-task:1.25
    docker-workflow:1.17
    google-source-plugin:0.3
    google-login:1.4
    prometheus:1.2.2
    authorize-project:1.3.0